// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// optimize_layout_cpp
void optimize_layout_cpp(Rcpp::NumericMatrix& embedding, const Rcpp::IntegerVector& positive_head, const Rcpp::IntegerVector& positive_tail, int n_epochs, int n_vertices, const Rcpp::NumericVector& epochs_per_sample, double a, double b, double gamma, double initial_alpha, double negative_sample_rate, bool verbose);
RcppExport SEXP _uwot_optimize_layout_cpp(SEXP embeddingSEXP, SEXP positive_headSEXP, SEXP positive_tailSEXP, SEXP n_epochsSEXP, SEXP n_verticesSEXP, SEXP epochs_per_sampleSEXP, SEXP aSEXP, SEXP bSEXP, SEXP gammaSEXP, SEXP initial_alphaSEXP, SEXP negative_sample_rateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type embedding(embeddingSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type positive_head(positive_headSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type positive_tail(positive_tailSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< int >::type n_vertices(n_verticesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type epochs_per_sample(epochs_per_sampleSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type initial_alpha(initial_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type negative_sample_rate(negative_sample_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    optimize_layout_cpp(embedding, positive_head, positive_tail, n_epochs, n_vertices, epochs_per_sample, a, b, gamma, initial_alpha, negative_sample_rate, verbose);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uwot_optimize_layout_cpp", (DL_FUNC) &_uwot_optimize_layout_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_uwot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
